import type { Completion } from '@codemirror/autocomplete';

export const CODE_EDITOR_THEME_OPTIONS = [
  { label: 'VSCode Dark', value: 'vscode-dark' },
  { label: 'VSCode Light', value: 'vscode-light' },
];

export const CODE_EDITOR_THEME_LABEL_MAP: Record<'vscode-dark' | 'vscode-light', string> = {
  'vscode-dark': 'VSCode Dark',
  'vscode-light': 'VSCode Light',
};

export const CODE_EDITOR_JS_GLOBAL_COMPLETIONS: Completion[] = [
  { label: 'console', type: 'variable' },
  { label: 'console.log', type: 'function' },
  { label: 'console.error', type: 'function' },
  { label: 'console.warn', type: 'function' },
  { label: 'window', type: 'variable' },
  { label: 'document', type: 'variable' },
  { label: 'localStorage', type: 'variable' },
  { label: 'sessionStorage', type: 'variable' },
  { label: 'setTimeout', type: 'function' },
  { label: 'setInterval', type: 'function' },
  { label: 'Promise', type: 'class' },
  { label: 'fetch', type: 'function' },
  { label: 'JSON.stringify', type: 'function' },
  { label: 'JSON.parse', type: 'function' },
  { label: 'Math', type: 'class' },
  { label: 'Array', type: 'class' },
  { label: 'Object', type: 'class' },
  { label: 'String', type: 'class' },
  { label: 'Number', type: 'class' },
  { label: 'Boolean', type: 'class' },
  {
    label: 'dataHub',
    type: 'variable',
    detail: '代码节点只读上下文',
    info: '预览运行时注入：可读取组件状态，不能直接写入组件。',
  },
  {
    label: 'dataHub.getComponentState',
    type: 'function',
    detail: '(componentKey) => ComponentState | undefined',
    info: '读取某个组件的完整状态对象（含 props/lifetimes）。',
  },
  {
    label: 'dataHub.getComponentStateByRef',
    type: 'function',
    detail: '(componentRef) => ComponentState | undefined',
    info: '按作用域引用读取组件状态（推荐，避免 key 冲突）。',
  },
  {
    label: 'dataHub.getComponentProp',
    type: 'function',
    detail: '(componentKey, propKey) => unknown',
    info: '读取某个组件的单个属性值。',
  },
  {
    label: 'dataHub.getComponentPropByRef',
    type: 'function',
    detail: '(componentRef, propKey) => unknown',
    info: '按作用域引用读取组件属性（推荐，避免 key 冲突）。',
  },
  {
    label: 'dataHub.composeRef',
    type: 'function',
    detail: '(componentKey) => componentRef',
    info: '将组件 key 转为当前作用域的 componentRef。',
  },
  {
    label: 'dataHub.scopeId',
    type: 'property',
    detail: '当前运行时作用域',
    info: '代码节点上下文绑定的组件作用域标识。',
  },
  {
    label: 'dataHub.getAllComponentStates',
    type: 'function',
    detail: '() => ComponentState[]',
    info: '读取当前页面全部组件状态快照。',
  },
  {
    label: 'dataHub.router',
    type: 'variable',
    detail: '路由控制上下文',
    info: '支持路由读取与跳转：current/push/replace/back/subscribe。',
  },
  {
    label: 'dataHub.router.current',
    type: 'function',
    detail: '() => { path, routeId, matched }',
    info: '读取当前路由状态。',
  },
  {
    label: 'dataHub.router.push',
    type: 'function',
    detail: '(path, params?) => boolean',
    info: '前进跳转到目标路由，例如 dataHub.router.push("/order", { id: 1 })。',
  },
  {
    label: 'dataHub.router.replace',
    type: 'function',
    detail: '(path, params?) => boolean',
    info: '替换当前历史记录并跳转。',
  },
  {
    label: 'dataHub.router.back',
    type: 'function',
    detail: '() => void',
    info: '返回上一条历史记录。',
  },
  {
    label: 'dataHub.router.subscribe',
    type: 'function',
    detail: '(listener) => unsubscribe',
    info: '监听路由状态变化，返回取消监听函数。',
  },
  {
    label: 'dataHub.cloud',
    type: 'variable',
    detail: '云函数调用上下文',
    info: '在代码节点中调用云函数，默认使用 /api/cloud-functions/:functionId/execute 接口。',
  },
  {
    label: 'dataHub.cloud.invoke',
    type: 'function',
    detail: "(functionIdOrName, payload?, options?) => Promise<unknown>",
    info: "调用云函数，示例：await dataHub.cloud.invoke('fn_xxx', { userId: 1 })。",
  },
  {
    label: "await dataHub.cloud.invoke('fn_xxx', { userId: 1 })",
    type: 'snippet',
    detail: '异步调用云函数',
    info: '推荐在 async 代码节点里 await 调用，再 return patch 向下游传递。',
  },
  {
    label: "const res = await dataHub.cloud.invoke('fn_xxx', { page: 1 }); return { dataSource: res.output };",
    type: 'snippet',
    detail: '云函数结果驱动组件数据源',
    info: 'execute 接口默认返回 { output }，可将 output 回填到表格/图表的 dataSource。',
  },
  {
    label: "return { dataSource: [{ name: 'Mon', value: 120 }, { name: 'Tue', value: 200 }] }",
    type: 'snippet',
    detail: '图表/Table 更新示例',
    info: '代码节点返回对象后会作为 patch 下发到下游组件，常用于刷新 Line/Bar/Pie 等图表和表格数据。',
  },
  {
    label: "return { dataSource: [{ name: 'North', value: 320 }, { name: 'South', value: 260 }] }",
    type: 'snippet',
    detail: '多图表通用 patch',
    info: '18 种图表组件共用 dataSource patch 协议，代码节点返回对象后可统一驱动刷新。',
  },
  {
    label: "const res = await dataHub.cloud.invoke('fn_dashboard', { range: '7d' }); return { dataSource: res.output ?? [] };",
    type: 'snippet',
    detail: '云函数结果映射图表',
    info: '推荐用 output 作为统一响应字段，再通过 return { dataSource } 驱动任意图表刷新。',
  },
  {
    label: "return { dataSource: [{ name: '2026-03-01', open: 12, close: 15, low: 10, high: 18 }] }",
    type: 'snippet',
    detail: 'K线图 patch 示例',
    info: 'CandlestickChart 推荐字段：name/open/close/low/high，可在属性面板调整字段映射。',
  },
  {
    label: "return { dataSource: [{ name: '北京市', value: 120 }, { name: '上海市', value: 98 }] }",
    type: 'snippet',
    detail: '地图图表 patch 示例',
    info: 'MapChart 推荐字段：name/value，默认 mapName=china，可通过 option 覆盖地图配置。',
  },
  {
    label: 'ctx',
    type: 'variable',
    detail: '当前触发上下文',
    info: '包含 event/upstreamNodeId/currentNodeId。',
  },
  {
    label: 'ctx.event',
    type: 'property',
    detail: '触发事件对象',
    info: '可能是生命周期事件或上游 patch 事件。',
  },
  {
    label: 'ctx.response',
    type: 'property',
    detail: '网络请求响应数据',
    info: '当上游为网络请求节点时，按 responsePath 注入的响应数据。',
  },
  {
    label: 'ctx.request',
    type: 'property',
    detail: '网络请求元信息',
    info: '包含 method/endpoint/status/ok/durationMs 等请求结果信息。',
  },
  {
    label: 'ctx.upstreamNodeId',
    type: 'property',
    detail: '上游节点 id',
    info: '当前代码节点的直接上游流程节点 id。',
  },
  {
    label: 'ctx.currentNodeId',
    type: 'property',
    detail: '当前代码节点 id',
    info: '当前正在执行的代码节点 id。',
  },
  {
    label: 'return { visible: true }',
    type: 'snippet',
    detail: '声明式返回 patch',
    info: '返回对象会被作为 patch 下发到下游组件节点。',
  },
];